pompano-beach-florida-flight-school:
  city: "Pompano Beach"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Butterfly World"
  point_of_interest_2: "Pompano Beach"

fort-lauderdale-florida-flight-school:
  city: "Fort Lauderdale"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Las Olas Boulevard"
  point_of_interest_2: "Hugh Taylor Birch State Park"

west-palm-beach-florida-flight-school:
  city: "West Palm Beach"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Palm Beach Zoo"
  point_of_interest_2: "Clematis Street"

boca-raton-florida-flight-school:
  city: "Boca Raton"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Mizner Park"
  point_of_interest_2: "Boca Raton Museum of Art"

delray-beach-florida-flight-school:
  city: "Delray Beach"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Atlantic Avenue"
  point_of_interest_2: "Wakoda Hatchee Preserve"

deerfield-beach-florida-flight-school:
  city: "Deerfield Beach"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Boca Raton Historical Society & Museum"
  point_of_interest_2: "Hillsboro Beach"

boynton-beach-florida-flight-school:
  city: "Boynton Beach"
  state: "Florida"
  state_short: "FL"
  point_of_interest_1: "Boynton Beach Oceanfront Park"
  point_of_interest_2: "Daggerwing Nature Center"
